=== frank007love/SAMT/WebContent/xsd/AAProfile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="jaxb.example"
	targetNamespace="jaxb.example" elementFormDefault="qualified"> -->
<xs:schema targetNamespace="jaxb.aaprofile.manager.samt.csie.ntut" elementFormDefault="qualified" xmlns="jaxb.aaprofile.manager.samt.csie.ntut"
 xmlns:xs="http://www.w3.org/2001/XMLSchema">	 
 
	<xs:element name="AAProfile" type="AAProfile"></xs:element>

	<xs:complexType name="AAProfile">
		<xs:sequence>
			<xs:element name="Accounts" type="Accounts" maxOccurs="1"
				minOccurs="0">
			</xs:element>
			<xs:element name="Groups" type="Groups" maxOccurs="1"
				minOccurs="0">
			</xs:element>

			<xs:element name="Permissions" type="Permissions"
				maxOccurs="1" minOccurs="0">
			</xs:element>

			<xs:element name="FolderList" type="FolderList" maxOccurs="1" minOccurs="0"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Account">
		<xs:attribute name="id" type="xs:string"></xs:attribute>
		<xs:attribute name="passwd" type="xs:string"></xs:attribute>
	</xs:complexType>


    <xs:complexType name="Accounts">
    	<xs:sequence>
			<xs:element name="Account" type="Account" minOccurs="0"
				maxOccurs="unbounded">
			</xs:element>
        </xs:sequence>
    </xs:complexType>
    

    <xs:complexType name="Groups">
    	<xs:sequence>
    		<xs:element name="Group" type="Group" maxOccurs="unbounded"
    			minOccurs="0">
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="Group">
    	<xs:sequence>
    		<xs:element name="GroupMebmer" type="GroupMember" maxOccurs="unbounded"
    			minOccurs="0"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="id" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="GroupMember">
    	<xs:attribute name="id" type="xs:string"></xs:attribute>
    	<xs:attribute name="type" type="xs:string"></xs:attribute>
    </xs:complexType>



    <xs:complexType name="Permissions">
    	<xs:sequence>
    		<xs:element name="Path" type="Path" maxOccurs="unbounded"
    			minOccurs="0">
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="Path">
    	<xs:sequence>
    		<xs:element name="PathMember" type="PathMember"
    			maxOccurs="unbounded" minOccurs="0">
    		</xs:element>
    	</xs:sequence>
    	<xs:attribute name="name" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="PathMember">
    	<xs:attribute name="id" type="xs:string"></xs:attribute>
    	<xs:attribute name="type" type="xs:string"></xs:attribute>
    	<xs:attribute name="read" type="xs:boolean"></xs:attribute>
    	<xs:attribute name="write" type="xs:boolean"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="FolderList">
    	<xs:sequence>
    		<xs:element name="Folder" type="Folder" maxOccurs="unbounded" minOccurs="0"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="Folder">
    	<xs:attribute name="name" type="xs:string"></xs:attribute>
    	<xs:attribute name="path" type="xs:string"></xs:attribute>
    </xs:complexType>

</xs:schema>

=== frank007love/SAMT/WebContent/TestFile/AAProfile.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:AAProfile xmlns:p="jaxb.aaprofile.manager.samt.csie.ntut" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="jaxb.aaprofile.manager.samt.csie.ntut AAProfile.xsd ">
  <p:Accounts>
    <p:Account id="oph" passwd="1234"/>
    <p:Account id="ztgao" passwd="1234"/>
    <p:Account id="tshsu" passwd="1234"/>
    <p:Account id="yc" passwd="1234"/>
    <p:Account id="ctchen" passwd="1234"/>
    <p:Account id="franklin" passwd="1234"/>
    <p:Account id="lenwind" passwd="1234"/>
    <p:Account id="frankcheng" passwd="1234"/>
  </p:Accounts>
  <p:Groups>
      <p:Group id="admin">
      	<p:GroupMebmer id="95" type="Group"/>
      	<p:GroupMebmer id="tshsu" type="User"/>
		<p:GroupMebmer id="ctchen" type="User"/>
      </p:Group>
      <p:Group id="96">
      	<p:GroupMebmer id="franklin" type="User"/>
      	<p:GroupMebmer id="lenwind" type="User"/>
      	<p:GroupMebmer id="frankcheng" type="User"/>     
      </p:Group>
      <p:Group id="95">
      	<p:GroupMebmer id="oph" type="User"/>
      	<p:GroupMebmer id="ztgao" type="User"/>
      </p:Group>
      <p:Group id="old">
      	<p:GroupMebmer id="yc" type="User"/>
      	<p:GroupMebmer id="tshsu" type="User"/>
      	<p:GroupMebmer id="ctchen" type="User"/>
      </p:Group>
  </p:Groups>
   
  <p:Permissions>
    <p:Path name="/">
      <p:PathMember id="*" type="Group" read="true" write="false"/>
      <p:PathMember id="admin" type="Group" read="true" write="true"/>
    </p:Path> 	
    <p:Path name="/JCIS/Java">
      <p:PathMember id="95" type="Group" read="true" write="true"/>
      <p:PathMember id="96" type="Group" read="true" write="true"/>
      <p:PathMember id="yc" type="User" read="true" write="false"/>
    </p:Path>
    	<p:Path name="/JCIS/Test">
      <p:PathMember id="95" type="Group" read="true" write="true"/>
      <p:PathMember id="96" type="Group" read="true" write="true"/>
    </p:Path>
  </p:Permissions>
   
  <p:FolderList>
  	<p:Folder name="JCIS" path="/JCIS"></p:Folder>
  	<p:Folder name="Java" path="/JCIS/Java"></p:Folder>
  </p:FolderList>
</p:AAProfile>
